sudo: required
language: go
go:
- 1.14.x
script:
- curl -Lv https://github.com/bwaang/go-cli/releases/latest/download/go-cli -o go-cli
- chmod +x go-cli
- ./go-cli print this is a long comma separated message
- make build
- make test
deploy:
  provider: releases
  api_key:
    secure: z6Sdv6L0SETaxVbh1pB2yDWV7nXQVbOe0VqpZSR3w87g62oBp/8FX6nDotYgMziUyLSClCjWT2KIyimYZYj/MIft/28VEc6X2tL1X1ycZBOUkV+GZU240b6dElJe2AUwY2NUZBcv+WDIu8+Mt+/6MPF5xkX5v7wD7yIcq8S0dobdHcM6OW2MoXKOJnuXpdlfTxDhkdQgTrgw5XhdY370H45YfmU4nkP9ax1MDEGBPhr+f9C+TtVgTf4ao8xoCPOh3+BU2MD1ssGqZr6OeDADNPGHDGYnNAAXtL+XUMinwTrOXgqjujONO4PILElPVCDOW0e7DdR/3JTKnkAvfvzb+LsF5/+uCvyjUnIXTL4q8vXiXhbD/HIG0vnY47rWNwCdm/B31VoW1HSSAEr1Nhw+HAMUSS9r4g9qda8DZ49HiN/X8Nl79gC6phOybg0AA2+F+z4OQBRo7yY/IDoKEgCO6eLuaq8fwjRlVm+xnfzzkNeq/JKNyyuPW+Li9Nme2pyTQ7nkBHzrD7j5zhHC8VyY/9NkpW1CRXl1REp8Fq4AsfYv32Kp+QlEjLGJMP/p5gFksPt0DQD3I1ZzXsKe+fBDjUJnilKVxvWpkvxWL/WpuLZtF7Paju2aVcu17hNcfg7cq+v7mY2HkUySsHlCM86Ki4TiYe5S+/2tyuVI+0OwjKA=
  file: go-cli
  skip_cleanup: true
  on:
    tags: true
